# Generated by Django 5.2 on 2025-04-25 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('max_capacity', models.IntegerField()),
                ('current_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=20)),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'license_plate')},
            },
        ),
        migrations.CreateModel(
            name='ParkingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('direction', models.CharField(choices=[('in', 'Entry'), ('out', 'Exit')], max_length=10)),
                ('status', models.CharField(choices=[('granted', 'Granted'), ('denied', 'Denied')], max_length=10)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('parking_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.parkingarea')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='ParkingAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateField(auto_now_add=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('parking_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.parkingarea')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.vehicle')),
            ],
            options={
                'unique_together': {('vehicle', 'parking_area')},
            },
        ),
    ]
