# Generated by Django 5.2 on 2025-04-25 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access_control', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accesscard',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_cards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accesspermission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_permissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='access_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='access_control.accesspoint'),
        ),
        migrations.AddField(
            model_name='accesszone',
            name='access_points',
            field=models.ManyToManyField(related_name='zones', to='access_control.accesspoint'),
        ),
        migrations.AddField(
            model_name='accesspermission',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='access_control.accesszone'),
        ),
        migrations.AddField(
            model_name='visitoraccess',
            name='access_zones',
            field=models.ManyToManyField(to='access_control.accesszone'),
        ),
        migrations.AddField(
            model_name='visitoraccess',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_visitors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='visitoraccess',
            name='visitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesses', to='access_control.visitor'),
        ),
        migrations.AlterUniqueTogether(
            name='accesspermission',
            unique_together={('user', 'zone')},
        ),
    ]
